---

# http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
aptcachetime: 3600
locale: "en_US.UTF-8"
timezone: "Asia/Beirut"
chromium:
  set_default: false
  policy: false
  extensions: false
ssh:
  start: true
  service_enabled: true
  password_auth: false
  root_login: false
