---

- name: Installing forticlient apt-key
  apt_key: 
    url: https://repo.fortinet.com/repo/ubuntu/DEB-GPG-KEY
    state: present

- name: Add forticlient deb repository
  apt_repository:
    repo: "deb [arch=amd64] https://repo.fortinet.com/repo/ubuntu/ /bionic multiverse"
    state: present

- name: Install forticlient
  apt:
    update_cache: yes
    state: latest
    name:
      - forticlient
