---

- name: Install awscli package
  pip: 
    name: awscli 
    state: latest

- name: Installing Amazon ECS command line
  get_url:
    url: https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
    dest: /usr/local/bin/ecs-cli
    mode: 0755

- name: Installed ECS version
  command: /usr/local/bin/ecs-cli --version


- name: Check if ktail is installed
  shell: which ktail
  register: ktail
  failed_when: ktail.rc > 1
  changed_when: ktail.rc == 1

- name: Download ktail
  get_url:
    url: https://github.com/atombender/ktail/releases/download/v0.7.0/ktail-linux-amd64
    dest: /usr/local/bin/ktail
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0775'
  when: ktail.rc == 1
