---

- name: Adding UNetbootin PPA
  apt_repository:
    repo: 'ppa:gezakovacs/ppa'


- name: Adding Kid3 PPA
  apt_repository:
    repo: 'ppa:ufleisch/kid3'


- name: Install common desktop packages
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
    name:
    - bleachbit
    - kid3 # audio files metadata management
    - byzanz # screen recording
    - geany
    - libnotify-bin
    - inotify-tools
    - meld # Diff / merge tool
    - cifs-utils
    - mpv
    - rxvt-unicode-256color
    - sox # to play sounds
    - ubuntu-restricted-extras # MP3, Microsoft fonts, Flash plugin, LAME and DVD playback
    - unetbootin # create bootable USB drives
    - wmctrl # to control windows
    - xclip # to manipulate the clipboard
    - xdotool # to control windows


- name: Install vlc
  snap:
    name: vlc


- name: Install yakuake
  snap:
    name: yakuake
    channel: candidate
