
- name: Install VSCode
  snap:
    name: code
    classic: yes

- name: Create VSCode Alias
  copy:
    src: code
    dest: /usr/bin/code
    mode: '0777'
    owner: root
    group: root

- name: Set VSCode as default editor
  command: update-alternatives --install /usr/bin/editor editor /usr/bin/code 100
  when: vscode.set_default == true

- name: Set VSCode to open plain text files
  command: xdg-mime default code.desktop text/plain
  when: vscode.set_default == true
