---

- name: Installing sublime text 3 apt-key
  apt_key: 
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Add google cloud sdk deb repository
  apt_repository:
    repo: "deb https://download.sublimetext.com/ apt/stable/"
    filename: sublime-text

- name: Install google cloud sdk
  apt:
    update_cache: yes
    state: latest
    name: sublime-text

- name: Prepare sublime directories (1/2)
  file: path="{{ ansible_env.HOME }}/.config/sublime-text-3/Installed Packages" state=directory owner="{{ ansible_env.USER }}" group="{{ ansible_env.USER }}"

- name: Prepare sublime directories (2/2)
  file: path="{{ ansible_env.HOME }}/.config/sublime-text-3/Packages/User" state=directory owner="{{ ansible_env.USER }}" group="{{ ansible_env.USER }}"

- name: Install Package Control for sublime
  get_url: url="https://packagecontrol.io/Package%20Control.sublime-package" dest="{{ ansible_env.HOME }}/.config/sublime-text-3/Installed Packages/Package Control.sublime-package"

- name: Copy Package Control settings template for auto-install (REMEMBER TO RUN DOTFILES SYMLINKS FOR REAL AUTO INSTALL PACKAGES)
  copy: src="Package Control.sublime-settings" dest="{{ ansible_env.HOME }}/.config/sublime-text-3/Packages/User/Package Control.sublime-settings" owner="{{ ansible_env.USER }}" group="{{ ansible_env.USER }}"
