---

- name: Install snapd package
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
    name: snapd

- name: Install slack
  snap:
    name: slack
    classic: yes
