---

- name: pre anaconda installation tasks
# ===============
  when: "anaconda_state == 'present'"

  block:

  - name: pre - ensure anaconda folders exist
    file:
      dest: "{{ item }}"
      state: directory
    with_items:
      - "{{ anaconda_installer_dir }}"
      - "{{ anaconda_home_dir }}"
  - name: pre - ensure anaconda installer file exists
    get_url:
      url: "{{ anaconda_installer_uri }}"
      dest: "{{ anaconda_installer_file }}"
      force: False
      checksum: "md5:{{ anaconda_installer_md5 }}"
      timeout: 300
  - name: pre - link anaconda installer file to anaconda home
    file:
      src: "{{ anaconda_installer_file }}"
      dest: "{{ anaconda_home_dir }}/installer.sh"
      state: link
    register: installer
  - name: pre - write a note for anaconda installer
    copy:
      dest: "{{ anaconda_home_dir }}/installer.README.txt"
      content: |
        Do not touch the linked file because ansible 
        uses it to decide if a reinstallation 
        (uninstall/install) is necessary.
  - name: pre - remove anaconda installation for a new install
    # if the installer file changes, we assume a new version should be installed
    # (the Anaconda way recommend a 'conda update' or similar instead of a new
    # installation but we won't to that here to keep it simple stupid)
    when: installer is changed
    file:
      dest: "{{ anaconda_install_dir }}"
      state: absent

  rescue:
    - fail:
        msg: "failed to prepare installation. installer file may be changed. a pre-installed anaconda may be removed."


- name: install anaconda
# =============
  when: "anaconda_state == 'present' and (installer is changed or anaconda_force_install)"

  block:
  - name: install - run installer
    command: "bash {{ anaconda_home_dir }}/installer.sh -b -p {{ anaconda_install_dir }} {{ anaconda_force_install|ternary('-f', '') }}"
    failed_when: false
    register: installer_out
  - name: install - fail if installer finished unsuccessfully
    fail:
      msg: "{{ installer_out.stderr }}"
    when: "not (('ERROR: File or directory already exists' in installer_out.stderr) or ('installation finished.' in installer_out.stdout))"

  rescue:
    - fail:
        msg: "Installation failed!"


- name: post tasks
# ================
  when: "anaconda_state == 'present' and anaconda_set_path|bool"

  block:
  - name: Ensure group "anaconda" exists
    group:
      name: anaconda
      state: present

  - name: Recursively change ownership of anaconda
    file:
      path: "{{ anaconda_home_dir }}"
      state: directory
      recurse: yes
      group: anaconda
      mode: '0770'

  - name: "adding existing user {{ ansible_user }} to group anaconda"
    user:
      name: "{{ ansible_user }}"
      shell: /bin/bash
      groups:
        - anaconda
      append: yes

  - name: post - set path to anaconda
    lineinfile:
      dest: "{{ item }}"
      create: true
      state: present
      insertafter: EOF
      line: 'export PATH="{{ anaconda_install_dir }}/bin:$PATH"'
    with_items:
      - /etc/bash.bashrc

  - name: post - install pip packages
    pip:
      name:
        - click
        - isort
        - pylint
        - pylint-django
        - pyinvoke
        - speedtest-cli
        - yapf
      state: latest
      executable: /opt/anaconda/dist/bin/pip

- name: uninstall
# ===============
  when: anaconda_state == 'absent'

  block:
  - name: uninstall - remove Anaconda home dir
    file:
      dest: "{{ anaconda_home_dir }}"
      state: absent
  - name: uninstall - remove path to anaconda
    lineinfile:
      dest: "{{ item }}"
      create: true
      state: absent
      line: 'export PATH="{{ anaconda_install_dir }}/bin:$PATH"'
    with_items:
      - /etc/bash.bashrc
